// Code generated by protoc-gen-go-cgrpc. DO NOT EDIT.
// version:
// 	protoc-gen-go-cgrpc v0.0.116<br />
// 	protoc              v5.27.0<br />
// source: api/admin_initialize.proto<br />

package api
