// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/admin_permission.proto

// @ts-nocheck


export class GetUserPermissionResp{
	canread?: boolean
	canwrite?: boolean
	admin?: boolean

	constructor(){}

	fromJSON(obj: Record<string,any>):void{
		if("canread" in obj){
			if(typeof obj["canread"] != 'boolean'){
				throw "response parse failed"
			}
			this.canread=obj["canread"]
		}
		if("canwrite" in obj){
			if(typeof obj["canwrite"] != 'boolean'){
				throw "response parse failed"
			}
			this.canwrite=obj["canwrite"]
		}
		if("admin" in obj){
			if(typeof obj["admin"] != 'boolean'){
				throw "response parse failed"
			}
			this.admin=obj["admin"]
		}
	}
}
