// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.141
// 	protoc             v7.34.0
// source: api/admin_user.proto

// @ts-nocheck


//must use the replacer in JSON.stringify() below:
/*
(key,value)=>{
	if(typeof value === "bigint"){
		return value.toString()
	}else if(value instanceof Map){
		return Object.fromEntries(value)
	}else if(value instanceof Uint8Array){
		let binary=''
		let chunkSize=1024
		for(let i = 0;i<value.length;i+=chunkSize){
			let chunk=value.subarray(i,i+chunkSize)
			binary += String.fromCharCode.apply(null,chunk)
		}
		return window.btoa(binary)
	}
	return value
}
*/
export class LoginInfoReq{

	constructor(){}

	toJSON():any{
		let copy = Object.assign({},this) as any
		Object.keys(copy).forEach(key=>{
			if(copy[key] === undefined || copy[key] === null){
				delete copy[key]
			}
		})
		return copy
	}
}
