// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.141
// 	protoc             v7.34.0
// source: api/admin_initialize.proto

// @ts-nocheck


export class InitStatusResp{
	status?: boolean//true-already inited,false-not inited

	constructor(){}

	fromJSON(obj: Record<string,any>):void{
		if("status" in obj){
			if(typeof obj["status"] != 'boolean'){
				throw "response parse failed"
			}
			this.status=obj["status"]
		}
	}
}
