// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/admin_user.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {jsonreplacer,normal_fetch} from './browser_method_util'
import {KickProjectReq} from './browser_message_admin_KickProjectReq'
import {KickProjectResp} from './browser_message_admin_KickProjectResp'

const _WebPathUserKickProject: string ="/admin.User/KickProject";

//timeout's unit is ms,it will be used when > 0
export async function KickProject(baseurl: string,req: KickProjectReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|KickProjectResp>{
	h = {...h,'Content-Type':'application/json'}
	let opts: RequestInit = {method:"POST",headers:h}
	opts.body=JSON.stringify(req,jsonreplacer)
	return normal_fetch(timeout,baseurl,_WebPathUserKickProject,'',opts,KickProjectResp)
}
