// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/admin_app.proto

// @ts-nocheck


//must use the replacer in JSON.stringify() below:
/*
(key,value)=>{
	if(typeof value === "bigint"){
		return value.toString()
	}else if(value instanceof Map){
		return Object.fromEntries(value)
	}else if(value instanceof Uint8Array){
		let binary=''
		let chunkSize=1024
		for(let i = 0;i<value.length;i+=chunkSize){
			let chunk=value.subarray(i,i+chunkSize)
			binary += String.fromCharCode.apply(null,chunk)
		}
		return window.btoa(binary)
	}
	return value
}
*/
export class WatchConfigReq{
	/*if this is in a request,the following rules must be obeyed
		value's length must >0
	*/
	project_name?: string
	/*if this is in a request,the following rules must be obeyed
		value's length must >0
	*/
	g_name?: string
	/*if this is in a request,the following rules must be obeyed
		value's length must >0
	*/
	a_name?: string
	/*if this is in a request,the following rules must be obeyed
		length/size must >0
	*/
	//map's key is config's keyname,map's value is config's cur version
	//if cur version == 0 means return current active config
	//if all cur version is the newest,the request will block until a new version come
	//if some keys' version is the newest,and some keys' version is old,then the keys with old version will return newest version and datas,the newest's keys will only return version
	//Warning!!!map's value's type is uint32,be careful of sign(+) and overflow
	keys?: Map<string,number>//can't contain '.' in key

	constructor(){}

	toJSON():any{
		let copy = Object.assign({},this) as any
		Object.keys(copy).forEach(key=>{
			if(copy[key] === undefined || copy[key] === null){
				delete copy[key]
			}
		})
		return copy
	}
}
