// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/admin_permission.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {jsonreplacer,normal_fetch} from './browser_method_util'
import {GetUserPermissionReq} from './browser_message_admin_GetUserPermissionReq'
import {GetUserPermissionResp} from './browser_message_admin_GetUserPermissionResp'

const _WebPathPermissionGetUserPermission: string ="/admin.Permission/GetUserPermission";

//timeout's unit is ms,it will be used when > 0
export async function GetUserPermission(baseurl: string,req: GetUserPermissionReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|GetUserPermissionResp>{
	h = {...h,'Content-Type':'application/json'}
	let opts: RequestInit = {method:"POST",headers:h}
	opts.body=JSON.stringify(req,jsonreplacer)
	return normal_fetch(timeout,baseurl,_WebPathPermissionGetUserPermission,'',opts,GetUserPermissionResp)
}
