// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.142
// 	protoc             v7.35.1
// source: api/admin_user.proto

// @ts-nocheck


export class UpdateRoleResp{

	constructor(){}

	fromJSON(_obj: Record<string,any>):void{
	}
}
