// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/admin_app.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {jsonreplacer,normal_fetch} from './browser_method_util'
import {GetInstanceInfoReq} from './browser_message_admin_GetInstanceInfoReq'
import {GetInstanceInfoResp} from './browser_message_admin_GetInstanceInfoResp'

const _WebPathAppGetInstanceInfo: string ="/admin.App/GetInstanceInfo";

//timeout's unit is ms,it will be used when > 0
export async function GetInstanceInfo(baseurl: string,req: GetInstanceInfoReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|GetInstanceInfoResp>{
	h = {...h,'Content-Type':'application/json'}
	let opts: RequestInit = {method:"POST",headers:h}
	opts.body=JSON.stringify(req,jsonreplacer)
	return normal_fetch(timeout,baseurl,_WebPathAppGetInstanceInfo,'',opts,GetInstanceInfoResp)
}
