// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/admin_user.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {jsonreplacer,normal_fetch} from './browser_method_util'
import {SearchUsersReq} from './browser_message_admin_SearchUsersReq'
import {SearchUsersResp} from './browser_message_admin_SearchUsersResp'

const _WebPathUserSearchUsers: string ="/admin.User/SearchUsers";

//timeout's unit is ms,it will be used when > 0
export async function SearchUsers(baseurl: string,req: SearchUsersReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|SearchUsersResp>{
	h = {...h,'Content-Type':'application/json'}
	let opts: RequestInit = {method:"POST",headers:h}
	opts.body=JSON.stringify(req,jsonreplacer)
	return normal_fetch(timeout,baseurl,_WebPathUserSearchUsers,'',opts,SearchUsersResp)
}
