// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/admin_app.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {jsonreplacer,normal_fetch} from './browser_method_util'
import {UpdateAppSecretReq} from './browser_message_admin_UpdateAppSecretReq'
import {UpdateAppSecretResp} from './browser_message_admin_UpdateAppSecretResp'

const _WebPathAppUpdateAppSecret: string ="/admin.App/UpdateAppSecret";

//timeout's unit is ms,it will be used when > 0
export async function UpdateAppSecret(baseurl: string,req: UpdateAppSecretReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|UpdateAppSecretResp>{
	h = {...h,'Content-Type':'application/json'}
	let opts: RequestInit = {method:"POST",headers:h}
	opts.body=JSON.stringify(req,jsonreplacer)
	return normal_fetch(timeout,baseurl,_WebPathAppUpdateAppSecret,'',opts,UpdateAppSecretResp)
}
