// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/admin_app.proto

// @ts-nocheck

import type {ResponseError} from './browser_method_util'
import {jsonreplacer,normal_fetch} from './browser_method_util'
import {WatchConfigReq} from './browser_message_admin_WatchConfigReq'
import {WatchConfigResp} from './browser_message_admin_WatchConfigResp'

const _WebPathAppWatchConfig: string ="/admin.App/WatchConfig";

//timeout's unit is ms,it will be used when > 0
export async function WatchConfig(baseurl: string,req: WatchConfigReq,h: Record<string, string>={},timeout: number=0):Promise<ResponseError|WatchConfigResp>{
	h = {...h,'Content-Type':'application/json'}
	let opts: RequestInit = {method:"POST",headers:h}
	opts.body=JSON.stringify(req,jsonreplacer)
	return normal_fetch(timeout,baseurl,_WebPathAppWatchConfig,'',opts,WatchConfigResp)
}
