// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.140
// 	protoc             v7.34.0
// source: api/admin_app.proto

// @ts-nocheck

import {InstanceInfo} from './browser_message_admin_InstanceInfo'

export class GetInstanceInfoResp{
	info?: InstanceInfo

	constructor(){}

	fromJSON(obj: Record<string,any>):void{
		if("info" in obj){
			if(Object.prototype.toString.call(obj["info"]) != '[object Object]'){
				throw "response parse failed"
			}
			let tmp = new InstanceInfo()
			tmp.fromJSON(obj["info"])
			this.info=tmp
		}
	}
}
