// Code generated by protoc-gen-browser. DO NOT EDIT.
// versions:
// 	protoc-gen-browser v0.0.141
// 	protoc             v7.34.0
// source: api/admin_user.proto

// @ts-nocheck


export class RoleInfo{
	//Warning!!!Element type is uint32,be careful of sign(+) and overflow
	project_id?: Array<number>
	role_name?: string
	comment?: string
	//Warning!!!Type is uint32,be careful of sign(+) and overflow
	ctime?: number

	constructor(){}

	fromJSON(obj: Record<string,any>):void{
		if("project_id" in obj){
			if(!Array.isArray(obj["project_id"])){
				throw "response parse failed"
			}
			for(let v of obj["project_id"]){
				if(typeof v != 'number'){
					throw "response parse failed"
				}
			}
			this.project_id=obj["project_id"]
		}
		if("role_name" in obj){
			if(typeof obj["role_name"] != 'string'){
				throw "response parse failed"
			}
			this.role_name=obj["role_name"]
		}
		if("comment" in obj){
			if(typeof obj["comment"] != 'string'){
				throw "response parse failed"
			}
			this.comment=obj["comment"]
		}
		if("ctime" in obj){
			if(typeof obj["ctime"] != 'number'){
				throw "response parse failed"
			}
			this.ctime=obj["ctime"]
		}
	}
}
