// Code generated by protoc-gen-go-crpc. DO NOT EDIT.
// version:
// 	protoc-gen-go-crpc v0.0.1
// 	protoc             v3.21.1
// source: api/initialize.proto

package api

import (
	context "context"
	crpc "github.com/chenjie199234/Corelib/crpc"
	error1 "github.com/chenjie199234/Corelib/error"
	log "github.com/chenjie199234/Corelib/log"
	metadata "github.com/chenjie199234/Corelib/metadata"
	proto "google.golang.org/protobuf/proto"
)

var _CrpcPathInitializeInitialize = "/admin.initialize/initialize"

type InitializeCrpcClient interface {
	//初始化
	Initialize(context.Context, *InitializeReq) (*InitializeResp, error)
}

type initializeCrpcClient struct {
	cc *crpc.CrpcClient
}

func NewInitializeCrpcClient(c *crpc.CrpcClient) InitializeCrpcClient {
	return &initializeCrpcClient{cc: c}
}

func (c *initializeCrpcClient) Initialize(ctx context.Context, req *InitializeReq) (*InitializeResp, error) {
	if req == nil {
		return nil, error1.ErrReq
	}
	reqd, _ := proto.Marshal(req)
	respd, e := c.cc.Call(ctx, _CrpcPathInitializeInitialize, reqd, metadata.GetMetadata(ctx))
	if e != nil {
		return nil, e
	}
	resp := new(InitializeResp)
	if len(respd) == 0 {
		return resp, nil
	}
	if e := proto.Unmarshal(respd, resp); e != nil {
		return nil, error1.ErrResp
	}
	return resp, nil
}

type InitializeCrpcServer interface {
	//初始化
	Initialize(context.Context, *InitializeReq) (*InitializeResp, error)
}

func _Initialize_Initialize_CrpcHandler(handler func(context.Context, *InitializeReq) (*InitializeResp, error)) crpc.OutsideHandler {
	return func(ctx *crpc.Context) {
		req := new(InitializeReq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(error1.ErrReq)
			return
		}
		if errstr := req.Validate(); errstr != "" {
			log.Error(ctx, "[/admin.initialize/initialize]", errstr)
			ctx.Abort(error1.ErrReq)
			return
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(InitializeResp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func RegisterInitializeCrpcServer(engine *crpc.CrpcServer, svc InitializeCrpcServer, allmids map[string]crpc.OutsideHandler) {
	//avoid lint
	_ = allmids
	engine.RegisterHandler(_CrpcPathInitializeInitialize, _Initialize_Initialize_CrpcHandler(svc.Initialize))
}
